name: Test

permissions:
  contents: write

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  rust-test:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: vitest
        run: |
          pnpm install
          pnpm run build
          pnpm run bundle
          pnpm run test:run
      - name: setup deno
        uses: ./
        with:
          repo: https://github.com/denoland/deno
          version: latest
      - name: setup deno
        uses: ./
        with:
          repo: https://github.com/denoland/deno
          version: latest
      - name: setup ei
        uses: ./
        with:
          repo: https://github.com/ahaoboy/easy-install
          version: latest
          bin: ei
      - name: setup qjs-ng
        uses: ./
        with:
          repo: https://github.com/ahaoboy/quickjs-ng-build
          version: latest
          bin: qjs-ng
      - name: test setup
        run: |
          deno --version
          ei --version
          qjs -h
